#!/usr/bin/env python3
"""Generate the synthetic sample genome shipped in data/.

Not a real person. Autosomal genotypes are random at a density matching a modern
consumer array (~9 kb spacing, ~320k usable variants) so that the runs-of-homozygosity
filters behave the way they would on real data. Thirty-one homozygous runs are planted,
giving F_ROH around 1.3% with nothing above 4 Mb — the background-endogamy pattern.

The mitochondrial sequence is rCRS at every position the classifier inspects except
6776 T>C, so it should call H3 and exclude everything else.

    python3 tools/make_sample.py > data/sample-23andme.txt
"""
import random, sys
random.seed(20260907)
SPACING = 9000
CHR = {1:249250621,2:243199373,3:198022430,4:191154276,5:180915260,6:171115067,7:159138663,
       8:146364022,9:141213431,10:135534747,11:135006516,12:133851895,13:115169878,
       14:107349540,15:102531392,16:90354753,17:81195210,18:78077248,19:59128983,
       20:63025520,21:48129895,22:51304566}
SHORT = [(1,42.0),(1,190.5),(2,60.0),(2,140.2),(3,25.4),(3,160.9),(4,88.1),(5,12.7),(5,120.3),
         (6,44.6),(6,150.1),(7,33.9),(8,70.2),(9,110.4),(10,20.8),(10,99.3),(11,55.5),(12,80.7),
         (13,40.1),(14,66.9),(15,30.3),(16,12.2),(16,70.8),(17,45.5),(18,22.4),(19,15.9),
         (20,38.6),(21,20.1),(22,30.7),(4,150.6)]
RUNS = [(c, mb*1e6, (mb+random.uniform(1.15,1.9))*1e6) for c, mb in SHORT]
RUNS.append((7, 118.2e6, 120.7e6))
def in_run(c, p):
    return any(rc == c and a <= p <= b for rc, a, b in RUNS)
A = "ACGT"
w = sys.stdout.write
w("# This data file generated by deep-ancestry as a SYNTHETIC SAMPLE.\n")
w("# It is not a real person. Autosomal genotypes are random except for a planted\n")
w("# set of homozygous runs; the mitochondrial sequence is consistent with H3.\n")
w("# Format matches the 23andMe raw export: rsid, chromosome, position, genotype.\n")
w("# rsid\tchromosome\tposition\tgenotype\n")
i = 0
for c in range(1, 23):
    p = random.randint(5000, SPACING)
    while p < CHR[c] - 10000:
        i += 1
        a1 = random.choice(A)
        if in_run(c, p) or random.random() > 0.32:
            gt = a1 + a1
        else:
            gt = "".join(sorted(a1 + random.choice([x for x in A if x != a1])))
        if random.random() < 0.004:
            gt = "--"
        w("rs%d\t%d\t%d\t%s\n" % (1000000+i, c, p, gt))
        p += max(1000, int(random.gauss(SPACING, SPACING*0.35)))
p = 100000
while p < 155270560 - 10000:                       # chrX, hemizygous: a male sample
    i += 1
    w("rs%d\tX\t%d\t%s\n" % (1000000+i, p, random.choice(A)))
    p += max(1000, int(random.gauss(30000, 9000)))
p = 2650000
while p < 28000000:                                # chrY
    i += 1
    w("rs%d\tY\t%d\t%s\n" % (1000000+i, p, random.choice(A) if random.random() > 0.12 else "-"))
    p += max(500, int(random.gauss(17000, 6000)))
RCRS = {73:"A",150:"C",199:"T",204:"T",207:"G",239:"T",250:"T",285:"C",456:"C",462:"C",489:"T",
663:"A",709:"G",750:"A",769:"G",1189:"T",1243:"T",1438:"A",1719:"G",1736:"A",1811:"A",1888:"G",
2259:"C",2706:"A",3010:"G",3197:"T",3480:"A",3505:"A",4216:"T",4248:"T",4580:"G",4646:"T",
4769:"A",4793:"A",4824:"A",4883:"C",4917:"A",5046:"G",5178:"C",5656:"A",6026:"G",6221:"T",
6371:"C",6776:"C",7028:"C",7476:"C",7768:"A",8251:"G",8393:"C",8697:"G",8701:"A",8794:"C",
8860:"A",9055:"G",9477:"G",9540:"T",9716:"T",10034:"T",10398:"A",10400:"C",10463:"T",10873:"T",
11251:"A",11299:"T",11332:"C",11467:"A",11674:"C",11812:"A",11947:"A",12308:"A",12372:"G",
12612:"A",12633:"C",12705:"C",13263:"A",13368:"G",13617:"T",13708:"G",13966:"A",14167:"C",
14233:"A",14318:"T",14470:"T",14766:"C",14783:"T",14793:"A",14798:"T",14872:"C",14905:"G",
15043:"G",15301:"A",15326:"A",15452:"C",15607:"A",15693:"T",15884:"C",15907:"A",15928:"G",
16069:"C",16126:"T",16129:"G",16189:"T",16217:"T",16223:"C",16224:"T",16270:"C",16278:"C",
16290:"C",16311:"T",16319:"G",16327:"C",16343:"A",16362:"T",16391:"G"}
for pos in sorted(RCRS):
    i += 1
    w("rs%d\tMT\t%d\t%s\n" % (1000000+i, pos, RCRS[pos]))
for pos in range(100, 16500, 90):
    if pos in RCRS: continue
    i += 1
    w("rs%d\tMT\t%d\t%s\n" % (1000000+i, pos, random.choice(A)))

